### ISSUE TITLE
Date and Time serializations broken

### ISSUE THREAD

**Issue by shannryan** [kgiszczak/shale#7]
Hi. I think 18ebdce0c0fbe5b2bd804cd4cc5cee0d3370b4fb broke serializations of `Time` and `Date` classes

E.g. Date
```ruby
irb(main):006:0> require 'shale'
=> true
irb(main):007:1* class Person < Shale::Mapper
irb(main):008:1*   attribute :dob, Shale::Type::Date
irb(main):009:0> end
=> :dob=
irb(main):010:0> p = Person.new(dob: '2022-08-12')
=> #<Person:0x00007fba055250f0 @dob=#<Date: 2022-08-12 ((2459804j,0s,0n),+0s,2299161j)>>
irb(main):011:0> p.to_json
Traceback (most recent call last):
        25: from /Users/shan/.rbenv/versions/2.7.1/bin/irb:23:in `<main>'                    
        24: from /Users/shan/.rbenv/versions/2.7.1/bin/irb:23:in `load'                      
        23: from /Users/shan/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/irb-1.4.1/exe/irb:11:in `<top (required)>'
         6: from (irb):11:in `<main>'                                                               
         5: from /Users/shan/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/shale-0.7.0/lib/shale/type/complex.rb:705:in `to_json'
         4: from /Users/shan/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/shale-0.7.0/lib/shale/type/complex.rb:210:in `to_json'
         3: from /Users/shan/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/shale-0.7.0/lib/shale/type/complex.rb:118:in `as_json'
         2: from /Users/shan/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/shale-0.7.0/lib/shale/type/complex.rb:118:in `each_value'
         1: from /Users/shan/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/shale-0.7.0/lib/shale/type/complex.rb:159:in `block in as_json'
/Users/shan/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/shale-0.7.0/lib/shale/type/date.rb:35:in `as_json': wrong number of arguments (given 2, expected 1) (ArgumentError)
```

**Comment by kgiszczak** [comment]
Hi, thanks for reporting it, the fix is ready: https://www.shalerb.org/releases.html
